name: Build for supported os
on: push

jobs:
  build-app:
    strategy:
      matrix:
        os: [ macos-latest,ubuntu-latest, windows-latest ]
    name: Build the application
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - run: mvn -B package --file pom.xml
      - run: mkdir staging && cp app/build/installer/* staging
      - name: upload build result
        uses: actions/upload-artifact@v2
        with:
          name: RidesFX-${{matrix.os}}
          path: staging
